flags: {}
nix:
  packages:
  - binutils
  - git
  - zlib
  enable: false
extra-package-dbs: []
packages:
- .
extra-deps:
- cabal-doctest-1.0.2
- servant-0.11
- servant-client-0.11
- telegram-api-0.6.3.0
resolver: lts-8.12
